<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-05-16 08:56:18 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1888
ERROR - 2019-05-16 09:14:45 --> Página no encontrada: Maquinaria/obtener1
ERROR - 2019-05-16 09:14:45 --> Página no encontrada: Assets/images
ERROR - 2019-05-16 09:14:45 --> Página no encontrada: Assets/images
ERROR - 2019-05-16 14:36:34 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1888
ERROR - 2019-05-16 15:20:26 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 80
ERROR - 2019-05-16 15:20:26 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:20:26 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 80
ERROR - 2019-05-16 15:20:26 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:21:48 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 80
ERROR - 2019-05-16 15:21:48 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 80
ERROR - 2019-05-16 15:21:48 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:21:48 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:21:48 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 80
ERROR - 2019-05-16 15:21:48 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 80
ERROR - 2019-05-16 15:21:48 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:21:48 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:26:49 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:49 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:49 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:49 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:49 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:49 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:49 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:49 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:49 --> Severity: Notice --> Undefined variable: maximominimos C:\xampp\htdocs\master\application\views\MaximoMinimo\listarMaximoMinimo.php 121
ERROR - 2019-05-16 15:26:49 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\master\application\views\MaximoMinimo\listarMaximoMinimo.php 121
ERROR - 2019-05-16 15:26:50 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:50 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:50 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:50 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:50 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:50 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:50 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:50 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:26:50 --> Severity: Notice --> Undefined variable: maximominimos C:\xampp\htdocs\master\application\views\MaximoMinimo\listarMaximoMinimo.php 121
ERROR - 2019-05-16 15:26:50 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\master\application\views\MaximoMinimo\listarMaximoMinimo.php 121
ERROR - 2019-05-16 15:27:08 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:27:08 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:27:08 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:27:08 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:27:08 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:27:08 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:27:08 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:27:08 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:28:33 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:28:33 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:28:33 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:28:33 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:28:33 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:28:33 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:28:33 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:28:33 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:31:44 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1888
ERROR - 2019-05-16 15:31:54 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:31:54 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:31:54 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:31:54 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:31:54 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:31:55 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:31:55 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:31:55 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 61
ERROR - 2019-05-16 15:37:32 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:37:32 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:37:32 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:37:32 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:37:32 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:37:32 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:37:32 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:37:32 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:37:34 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:37:34 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:37:34 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:37:34 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:37:34 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:37:34 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:37:34 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:37:34 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:40:09 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:40:09 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:40:09 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:40:09 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:40:09 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:40:09 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:40:09 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:40:09 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:40:57 --> Severity: error --> Exception: Too few arguments to function MaximoMinimoPojo::__construct(), 19 passed in C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php on line 80 and exactly 21 expected C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoPojo.php 28
ERROR - 2019-05-16 15:42:03 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:42:03 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:42:03 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:42:03 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:42:03 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:42:03 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:42:03 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:42:03 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 73
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:43:17 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 74
ERROR - 2019-05-16 15:45:21 --> Severity: error --> Exception: Too few arguments to function MaximoMinimoPojo::__construct(), 17 passed in C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php on line 90 and exactly 21 expected C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoPojo.php 28
ERROR - 2019-05-16 15:49:06 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 86
ERROR - 2019-05-16 15:49:07 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 87
ERROR - 2019-05-16 15:49:07 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 86
ERROR - 2019-05-16 15:49:07 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 87
ERROR - 2019-05-16 15:54:29 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 86
ERROR - 2019-05-16 15:54:29 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 86
ERROR - 2019-05-16 15:54:29 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 87
ERROR - 2019-05-16 15:54:29 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 87
ERROR - 2019-05-16 15:54:29 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 86
ERROR - 2019-05-16 15:54:29 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 86
ERROR - 2019-05-16 15:54:29 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 87
ERROR - 2019-05-16 15:54:29 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 87
ERROR - 2019-05-16 15:57:15 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:57:15 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 15:57:15 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 15:57:15 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:06:26 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:06:26 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:06:26 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:06:26 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:06:26 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:06:26 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:06:26 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:06:26 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:06:52 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:06:52 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:06:52 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:06:52 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:06:52 --> Severity: Notice --> Undefined variable: suma_total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:06:52 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:06:52 --> Severity: Notice --> Undefined variable: suma_total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:06:52 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:15:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'b' at line 1 - Invalid query: b
ERROR - 2019-05-16 16:15:56 --> Severity: Notice --> Undefined variable: total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:15:56 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:15:56 --> Severity: Notice --> Undefined variable: total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:15:56 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:15:56 --> Severity: Notice --> Undefined variable: total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:15:56 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:15:56 --> Severity: Notice --> Undefined variable: total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:15:56 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:15:56 --> Severity: error --> Exception: Call to undefined method MaximoMinimoPojo::getSuma_total_requerido_mensual_con_oc_y_consignacion() C:\xampp\htdocs\master\application\views\MaximoMinimo\listarMaximoMinimo.php 162
ERROR - 2019-05-16 16:15:56 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\master\system\core\Exceptions.php:271) C:\xampp\htdocs\master\system\core\Common.php 570
ERROR - 2019-05-16 16:16:24 --> Severity: Notice --> Undefined variable: total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:16:24 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:16:24 --> Severity: Notice --> Undefined variable: total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:16:24 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:16:24 --> Severity: Notice --> Undefined variable: total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:16:24 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:16:24 --> Severity: Notice --> Undefined variable: total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:16:24 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:19:21 --> Severity: Notice --> Undefined variable: total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:19:21 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:19:21 --> Severity: Notice --> Undefined variable: total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:19:21 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:19:21 --> Severity: Notice --> Undefined variable: total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:19:21 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-16 16:19:21 --> Severity: Notice --> Undefined variable: total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-16 16:19:21 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
