<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-07-02 09:37:06 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1906
ERROR - 2019-07-02 09:37:28 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1906
ERROR - 2019-07-02 09:39:10 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1906
ERROR - 2019-07-02 10:18:18 --> Severity: Notice --> Undefined property: stdClass::$total_registros_alethia C:\xampp\htdocs\master\application\views\RecoleccionDatos\listarRecoleccionDatos.php 198
ERROR - 2019-07-02 10:18:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'compartida' at line 1 - Invalid query: SELECT COUNT(*) as total_registros_alethia_existente FROM recoleccion_datos r  where r.id=15 and r.identificador <> Información compartida
ERROR - 2019-07-02 10:19:27 --> Severity: Notice --> Undefined property: stdClass::$total_registros_alethia C:\xampp\htdocs\master\application\views\RecoleccionDatos\listarRecoleccionDatos.php 198
ERROR - 2019-07-02 10:24:26 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1906
ERROR - 2019-07-02 10:24:28 --> Severity: Notice --> Undefined variable: totalRegistroEmpresaAlethiaExistente C:\xampp\htdocs\master\application\views\RecoleccionDatos\listarRecoleccionDatos.php 440
ERROR - 2019-07-02 10:24:28 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\master\application\views\RecoleccionDatos\listarRecoleccionDatos.php 440
