<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-05-17 12:16:33 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1888
ERROR - 2019-05-17 12:16:36 --> Severity: Notice --> Undefined variable: total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:16:36 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:16:36 --> Severity: Notice --> Undefined variable: total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:16:36 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:16:36 --> Severity: Notice --> Undefined variable: total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:16:36 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:16:36 --> Severity: Notice --> Undefined variable: total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:16:36 --> Severity: Notice --> Undefined property: stdClass::$ C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:23:51 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:23:51 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:23:51 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:23:51 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:23:52 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:23:52 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:23:52 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:23:52 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:23:53 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:23:53 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:23:53 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:23:53 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:23:56 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:23:56 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:23:56 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:23:56 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:25:15 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:25:15 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:25:15 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:25:15 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:25:17 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:25:17 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:25:17 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:25:17 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:30 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:30 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:30 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:30 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:32 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:32 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:32 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:32 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:33 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:33 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:33 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:33 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:34 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:34 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:34 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:34 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:35 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:35 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:35 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:35 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:39 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:39 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:39 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:39 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:41 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:41 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:26:41 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:26:41 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:32 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:32 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:32 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:32 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:33 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:33 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:33 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:33 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:36 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:36 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:36 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:36 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:36 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:36 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:36 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:36 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:37 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:37 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:27:37 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:27:37 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:19 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:19 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:19 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:19 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:20 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:20 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:20 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:20 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:20 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:20 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:20 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:20 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:21 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:22 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:22 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:22 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:22 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:24 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:24 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:28:24 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_mensual_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 81
ERROR - 2019-05-17 12:28:24 --> Severity: Notice --> Undefined property: stdClass::$total_requerido_trimestral_con_oc_y_consignacion C:\xampp\htdocs\master\application\models\MaximoMinimo\MaximoMinimoModelo.php 82
ERROR - 2019-05-17 12:45:18 --> Severity: error --> Exception: Call to undefined method MaximoMinimoPojo::getTotal_requerido_mensual_con_oc_y_consignacion() C:\xampp\htdocs\master\application\views\MaximoMinimo\listarMaximoMinimo.php 162
ERROR - 2019-05-17 15:28:30 --> Severity: Notice --> Undefined property: stdClass::$fecha_requiera_piezas C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 61
ERROR - 2019-05-17 15:28:30 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 65
ERROR - 2019-05-17 15:28:30 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 66
ERROR - 2019-05-17 15:28:30 --> Severity: Notice --> Undefined property: stdClass::$pcfob C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 73
ERROR - 2019-05-17 15:28:30 --> Severity: error --> Exception: Call to undefined method ReporteMaximoMinimoPojo::getTotal_requerido_mensual() C:\xampp\htdocs\master\application\views\ReporteMaximoMinimo\listarMaximoMinimo.php 110
ERROR - 2019-05-17 15:49:35 --> Severity: Notice --> Undefined property: stdClass::$fecha_requiera_piezas C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 61
ERROR - 2019-05-17 15:49:35 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 65
ERROR - 2019-05-17 15:49:35 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 66
ERROR - 2019-05-17 15:49:35 --> Severity: Notice --> Undefined property: stdClass::$pcfob C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 73
ERROR - 2019-05-17 15:58:12 --> Severity: Notice --> Undefined property: stdClass::$fecha_requiera_piezas C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 61
ERROR - 2019-05-17 15:58:12 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 65
ERROR - 2019-05-17 15:58:12 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 66
ERROR - 2019-05-17 15:58:12 --> Severity: Notice --> Undefined property: stdClass::$pcfob C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 73
ERROR - 2019-05-17 16:03:05 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_or_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 65
ERROR - 2019-05-17 16:03:05 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_or_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 66
ERROR - 2019-05-17 16:03:05 --> Severity: Notice --> Undefined property: stdClass::$pcfob C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 73
ERROR - 2019-05-17 16:08:18 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_oc_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 65
ERROR - 2019-05-17 16:08:18 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_oc_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 66
ERROR - 2019-05-17 16:08:18 --> Severity: error --> Exception: Call to undefined method ReporteMaximoMinimoPojo::getSuma_total_requerido_mensual_con_oc_consignacion() C:\xampp\htdocs\master\application\views\ReporteMaximoMinimo\listarMaximoMinimo.php 128
ERROR - 2019-05-17 16:09:25 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_oc_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 65
ERROR - 2019-05-17 16:09:25 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_oc_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 66
ERROR - 2019-05-17 16:09:25 --> Severity: error --> Exception: Call to undefined method ReporteMaximoMinimoPojo::getSuma_total_requerido_mensual_con_oc_consignacion() C:\xampp\htdocs\master\application\views\ReporteMaximoMinimo\listarMaximoMinimo.php 128
ERROR - 2019-05-17 16:09:30 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_oc_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 65
ERROR - 2019-05-17 16:09:30 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_oc_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 66
ERROR - 2019-05-17 16:11:27 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_mensual_con_oc_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 65
ERROR - 2019-05-17 16:11:27 --> Severity: Notice --> Undefined property: stdClass::$suma_total_requerido_trimestral_con_oc_consignacion C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php 66
ERROR - 2019-05-17 16:11:27 --> Severity: error --> Exception: Too few arguments to function ReporteMaximoMinimoPojo::__construct(), 17 passed in C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php on line 74 and exactly 18 expected C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoPojo.php 25
ERROR - 2019-05-17 16:11:56 --> Severity: error --> Exception: Too few arguments to function ReporteMaximoMinimoPojo::__construct(), 17 passed in C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php on line 74 and exactly 18 expected C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoPojo.php 25
ERROR - 2019-05-17 16:11:57 --> Severity: error --> Exception: Too few arguments to function ReporteMaximoMinimoPojo::__construct(), 17 passed in C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php on line 74 and exactly 18 expected C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoPojo.php 25
ERROR - 2019-05-17 16:11:58 --> Severity: error --> Exception: Too few arguments to function ReporteMaximoMinimoPojo::__construct(), 17 passed in C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoModelo.php on line 74 and exactly 18 expected C:\xampp\htdocs\master\application\models\ReporteMaximoMinimo\ReporteMaximoMinimoPojo.php 25
ERROR - 2019-05-17 16:13:23 --> Severity: error --> Exception: Call to undefined method ReporteMaximoMinimoPojo::getSuma_total_requerido_trimestral_con_oc_consignacion() C:\xampp\htdocs\master\application\views\ReporteMaximoMinimo\listarMaximoMinimo.php 131
ERROR - 2019-05-17 16:20:40 --> Query error: Unknown column 'total_requerido_mensual' in 'field list' - Invalid query: SELECT SUM(total_requerido_mensual) total_requerido_mensual
FROM `mayo_2019_rotacion_inventario`
ERROR - 2019-05-17 17:00:24 --> Query error: Unknown column 'suma_total_requerido_mensual_con_oc_consignacion' in 'field list' - Invalid query: SELECT SUM(suma_total_requerido_mensual_con_oc_consignacion ) as total_requerido_mensual_con_or_cons
FROM `mayo_2019_rotacion_inventario`
ERROR - 2019-05-17 17:01:49 --> Query error: Unknown column 'suma_total_requerido_trimestral_con_oc_y_consignacion' in 'field list' - Invalid query: SELECT SUM(suma_total_requerido_trimestral_con_oc_y_consignacion) as total_requerido_trimestral_con_or_cons
FROM `rotacion_inventario_prueba`
