<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-09-19 08:32:29 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1906
ERROR - 2019-09-19 08:43:28 --> Severity: Notice --> Undefined property: stdClass::$ocv C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php 109
ERROR - 2019-09-19 08:43:28 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 54
ERROR - 2019-09-19 08:47:23 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 54
ERROR - 2019-09-19 08:48:21 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 08:53:44 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 08:56:31 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 08:56:32 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 08:58:24 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 09:10:05 --> Página no encontrada: Fucomptas/actualizar
ERROR - 2019-09-19 09:10:05 --> Página no encontrada: Assets/images
ERROR - 2019-09-19 09:10:05 --> Página no encontrada: Assets/images
ERROR - 2019-09-19 09:12:20 --> Severity: error --> Exception: Too few arguments to function Fucompras::eliminar(), 0 passed in C:\xampp\htdocs\master\system\core\CodeIgniter.php on line 532 and exactly 1 expected C:\xampp\htdocs\master\application\controllers\Fucompras.php 335
ERROR - 2019-09-19 09:27:59 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 11:50:05 --> Query error: Unknown column 'oc' in 'field list' - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `oc`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', NULL, NULL, '', NULL, '', '', '', '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 11:52:21 --> Query error: Column 'cliente_proveedor' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', NULL, NULL, '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 11:55:53 --> Query error: Column 'cliente_proveedor' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', NULL, NULL, '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 11:58:23 --> Query error: Column 'awb' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', NULL, '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 11:58:57 --> Query error: Column 'dta' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 12:00:03 --> Query error: Column 'iva_del_pedimento' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 12:00:15 --> Query error: Column 'iva_del_pedimento' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 12:01:02 --> Query error: Column 'iva_del_pedimento' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 12:04:40 --> Query error: Column 'iva_del_pedimento' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 12:07:04 --> Query error: Column 'costo_del_flete_usd' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 12:09:34 --> Query error: Column 'utilidad_refx_pz' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 12:11:47 --> Query error: Column 'utilidad_refx_pz' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', NULL, '', '1')
ERROR - 2019-09-19 14:06:58 --> Severity: Notice --> Undefined index: id C:\xampp\htdocs\master\application\controllers\Fucompras.php 310
ERROR - 2019-09-19 14:06:58 --> Query error: Column 'utilidad_refx_pz' cannot be null - Invalid query: INSERT INTO `fucompras` (`ref`, `estatus`, `compania_importadora`, `cliente_proveedor`, `awb`, `courier`, `clave`, `tipo_de_prod`, `descripcion`, `factura`, `imn`, `ocv`, `qty`, `pu_usd`, `total_usd`, `tipo_de_embarque`, `tc_pedimento`, `importacion_por_partida_pz_mxn`, `importacion_por_partida_pz_usd`, `impx_unidad`, `costo_total_compra_usd_lab_qro`, `costo_unitario_compra_usd_lab_qro`, `com`, `cm`, `cm_c`, `ent`, `pedimento`, `fecha_pedimento`, `valor_aduana`, `arancel_igi`, `arancel`, `dta`, `iva_del_pedimento`, `costo_del_flete_mxn`, `honorarios_courier`, `costo_del_flete_usd`, `pv_extra_bajo_ref_x_pz`, `utilidad_refx_pz`, `utilidad`, `observaciones`, `fecha_pi`, `codigo_arancelario`, `id`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', NULL, '', 0)
ERROR - 2019-09-19 14:08:04 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1906
ERROR - 2019-09-19 14:13:41 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 14:16:16 --> Severity: error --> Exception: Call to undefined method FucomprasPojo::getTipo_de_prod() C:\xampp\htdocs\master\application\views\Fucompras\listarFucompras.php 280
ERROR - 2019-09-19 14:24:48 --> Severity: Notice --> Undefined variable: fucompras C:\xampp\htdocs\master\application\views\Fucompras\listarFucompras.php 246
ERROR - 2019-09-19 14:24:48 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\master\application\views\Fucompras\listarFucompras.php 246
ERROR - 2019-09-19 14:25:08 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 14:52:40 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 14:52:52 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 55
ERROR - 2019-09-19 14:55:29 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 40
ERROR - 2019-09-19 14:55:36 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 29
ERROR - 2019-09-19 14:55:42 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 18
ERROR - 2019-09-19 14:56:25 --> Severity: Notice --> Undefined variable: fucompras C:\xampp\htdocs\master\application\views\Fucompras\listarFucompras.php 246
ERROR - 2019-09-19 14:56:25 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\master\application\views\Fucompras\listarFucompras.php 246
ERROR - 2019-09-19 14:57:10 --> Severity: Notice --> Undefined variable: fucompras C:\xampp\htdocs\master\application\views\Fucompras\listarFucompras.php 246
ERROR - 2019-09-19 14:57:10 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\master\application\views\Fucompras\listarFucompras.php 246
ERROR - 2019-09-19 15:00:59 --> Severity: error --> Exception: Call to undefined method FucomprasPojo::getCodigo_arancelario() C:\xampp\htdocs\master\application\views\Fucompras\listarFucompras.php 489
ERROR - 2019-09-19 15:03:03 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 56
ERROR - 2019-09-19 15:03:41 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 56
ERROR - 2019-09-19 15:03:42 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 56
ERROR - 2019-09-19 15:03:42 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 56
ERROR - 2019-09-19 15:04:05 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 56
ERROR - 2019-09-19 15:04:10 --> Severity: error --> Exception: Too few arguments to function FucomprasPojo::__construct(), 42 passed in C:\xampp\htdocs\master\application\models\Fucompras\FucomprasModelo.php on line 139 and exactly 43 expected C:\xampp\htdocs\master\application\models\Fucompras\Fucompraspojo.php 56
