<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-05-02 08:33:46 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1888
ERROR - 2019-05-02 15:52:15 --> Página no encontrada: Assets/images
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:12 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:13 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:14 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$grupo C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$referencia C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cantidad_maxima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$precio_unitario C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$vida_util_dias C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$periodo_surtimiento_vida_util C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$cantidad_minima C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$paqueteria C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tipo_entrega C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$dias_credito C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$pulgadas C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$diametro_rod_ml C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$maquina_cliente C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$capacitacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$capacitacion_fecha C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$piezas_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$costo_juego C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$juego_mensuales C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_comp C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$golpes_prom_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$beneficio_golpes_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_com C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:15 --> Severity: Notice --> Undefined property: stdClass::$tiempo_rot_rodicut C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$beneficio_rot_prom C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$precio_golpe C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$ciudad_planta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$observacion C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$marca_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$contacto C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$tipo_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$troquel C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$uso_de_cfdi C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$metodo_pago C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$fecha_visita C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$fecha_seguimiento C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$golpes_maquina C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$confirmacion_orden_compra C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$fecha_ultima_factura C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:57:16 --> Severity: Notice --> Undefined property: stdClass::$first_name C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 241
ERROR - 2019-05-02 15:58:35 --> Severity: error --> Exception: Too few arguments to function ClienteRefaccionesPojo::__construct(), 1 passed in C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php on line 241 and exactly 43 expected C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesPojo.php 61
ERROR - 2019-05-02 16:00:39 --> Severity: error --> Exception: Too few arguments to function ClienteRefaccionesPojo::__construct(), 1 passed in C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php on line 241 and exactly 43 expected C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesPojo.php 61
ERROR - 2019-05-02 16:01:06 --> Severity: error --> Exception: Too few arguments to function ClienteRefaccionesPojo::__construct(), 1 passed in C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php on line 241 and exactly 43 expected C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesPojo.php 61
ERROR - 2019-05-02 16:15:35 --> Severity: Notice --> Undefined property: stdClass::$id_venta C:\xampp\htdocs\master\application\models\ClienteRefacciones\ClienteRefaccionesModelo.php 243
ERROR - 2019-05-02 16:17:46 --> Severity: error --> Exception: syntax error, unexpected 'if' (T_IF), expecting ',' or ';' C:\xampp\htdocs\master\application\views\ClienteRefacciones\listarClienteRefacciones.php 108
ERROR - 2019-05-02 16:17:57 --> Severity: Notice --> Undefined variable: obj C:\xampp\htdocs\master\application\views\ClienteRefacciones\listarClienteRefacciones.php 109
ERROR - 2019-05-02 16:17:57 --> Severity: error --> Exception: Call to a member function getId_venta() on null C:\xampp\htdocs\master\application\views\ClienteRefacciones\listarClienteRefacciones.php 109
