<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-08-26 11:54:00 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1906
ERROR - 2019-08-26 11:54:26 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 11:54:26 --> Query error: Column 'foto' cannot be null - Invalid query: INSERT INTO `bitacora_mtto` (`planta`, `modelo`, `maquina`, `fecha`, `motivo_asistencia`, `tipo`, `mantenimiento`, `consecutivo`, `des_acti1`, `des_acti2`, `des_acti3`, `des_acti4`, `des_acti5`, `des_acti6`, `des_acti7`, `des_acti8`, `des_acti9`, `des_acti10`, `des_acti11`, `des_acti12`, `des_acti13`, `des_acti14`, `des_acti15`, `reporto`, `ref_usadas1`, `ref_usadas2`, `ref_usadas3`, `ref_usadas4`, `ref_usadas5`, `ref_usadas6`, `ref_usadas7`, `ref_usadas8`, `ref_usadas9`, `ref_usadas10`, `ref_usadas11`, `ref_usadas12`, `ref_usadas13`, `ref_usadas14`, `ref_usadas15`, `ref_usadas16`, `ref_usadas17`, `ref_usadas18`, `ref_usadas19`, `ref_usadas20`, `ref_usadas21`, `ref_usadas22`, `ref_usadas23`, `ref_usadas24`, `ref_usadas25`, `ref_usadas26`, `ref_usadas27`, `ref_usadas28`, `ref_usadas29`, `ref_usadas30`, `ref_recomen1`, `ref_recomen2`, `ref_recomen3`, `ref_recomen4`, `ref_recomen5`, `ref_recomen6`, `ref_recomen7`, `ref_recomen8`, `ref_recomen9`, `ref_recomen10`, `ref_recomen11`, `ref_recomen12`, `ref_recomen13`, `ref_recomen14`, `ref_recomen15`, `ref_recomen16`, `ref_recomen17`, `ref_recomen18`, `ref_recomen19`, `ref_recomen20`, `ref_recomen21`, `ref_recomen22`, `ref_recomen23`, `ref_recomen24`, `ref_recomen25`, `ref_recomen26`, `ref_recomen27`, `ref_recomen28`, `ref_recomen29`, `ref_recomen30`, `capacitacion`, `aceptacion_capacitacion`, `recomendaciones`, `proxima_inter`, `foto`, `id`) VALUES (' ', 'fxdbxgfd', '', '', 'bfdxb ', 'Garantía', '', '', 'fdgfgfd', '', 'gfd', 'gfd', 'gfd', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '1')
ERROR - 2019-08-26 11:54:26 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 11:54:26 --> Query error: Column 'foto' cannot be null - Invalid query: INSERT INTO `bitacora_mtto` (`planta`, `modelo`, `maquina`, `fecha`, `motivo_asistencia`, `tipo`, `mantenimiento`, `consecutivo`, `des_acti1`, `des_acti2`, `des_acti3`, `des_acti4`, `des_acti5`, `des_acti6`, `des_acti7`, `des_acti8`, `des_acti9`, `des_acti10`, `des_acti11`, `des_acti12`, `des_acti13`, `des_acti14`, `des_acti15`, `reporto`, `ref_usadas1`, `ref_usadas2`, `ref_usadas3`, `ref_usadas4`, `ref_usadas5`, `ref_usadas6`, `ref_usadas7`, `ref_usadas8`, `ref_usadas9`, `ref_usadas10`, `ref_usadas11`, `ref_usadas12`, `ref_usadas13`, `ref_usadas14`, `ref_usadas15`, `ref_usadas16`, `ref_usadas17`, `ref_usadas18`, `ref_usadas19`, `ref_usadas20`, `ref_usadas21`, `ref_usadas22`, `ref_usadas23`, `ref_usadas24`, `ref_usadas25`, `ref_usadas26`, `ref_usadas27`, `ref_usadas28`, `ref_usadas29`, `ref_usadas30`, `ref_recomen1`, `ref_recomen2`, `ref_recomen3`, `ref_recomen4`, `ref_recomen5`, `ref_recomen6`, `ref_recomen7`, `ref_recomen8`, `ref_recomen9`, `ref_recomen10`, `ref_recomen11`, `ref_recomen12`, `ref_recomen13`, `ref_recomen14`, `ref_recomen15`, `ref_recomen16`, `ref_recomen17`, `ref_recomen18`, `ref_recomen19`, `ref_recomen20`, `ref_recomen21`, `ref_recomen22`, `ref_recomen23`, `ref_recomen24`, `ref_recomen25`, `ref_recomen26`, `ref_recomen27`, `ref_recomen28`, `ref_recomen29`, `ref_recomen30`, `capacitacion`, `aceptacion_capacitacion`, `recomendaciones`, `proxima_inter`, `foto`, `id`) VALUES (' ', 'fxdbxgfd', '', '', 'bfdxb ', 'Garantía', '', '', 'fdgfgfd', '', 'gfd', 'gfd', 'gfd', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '1')
ERROR - 2019-08-26 11:55:16 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 11:55:16 --> Severity: Notice --> Undefined index: id C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 250
ERROR - 2019-08-26 11:55:16 --> Query error: Column 'foto' cannot be null - Invalid query: INSERT INTO `bitacora_mtto` (`planta`, `modelo`, `maquina`, `fecha`, `motivo_asistencia`, `tipo`, `mantenimiento`, `consecutivo`, `des_acti1`, `des_acti2`, `des_acti3`, `des_acti4`, `des_acti5`, `des_acti6`, `des_acti7`, `des_acti8`, `des_acti9`, `des_acti10`, `des_acti11`, `des_acti12`, `des_acti13`, `des_acti14`, `des_acti15`, `reporto`, `ref_usadas1`, `ref_usadas2`, `ref_usadas3`, `ref_usadas4`, `ref_usadas5`, `ref_usadas6`, `ref_usadas7`, `ref_usadas8`, `ref_usadas9`, `ref_usadas10`, `ref_usadas11`, `ref_usadas12`, `ref_usadas13`, `ref_usadas14`, `ref_usadas15`, `ref_usadas16`, `ref_usadas17`, `ref_usadas18`, `ref_usadas19`, `ref_usadas20`, `ref_usadas21`, `ref_usadas22`, `ref_usadas23`, `ref_usadas24`, `ref_usadas25`, `ref_usadas26`, `ref_usadas27`, `ref_usadas28`, `ref_usadas29`, `ref_usadas30`, `ref_recomen1`, `ref_recomen2`, `ref_recomen3`, `ref_recomen4`, `ref_recomen5`, `ref_recomen6`, `ref_recomen7`, `ref_recomen8`, `ref_recomen9`, `ref_recomen10`, `ref_recomen11`, `ref_recomen12`, `ref_recomen13`, `ref_recomen14`, `ref_recomen15`, `ref_recomen16`, `ref_recomen17`, `ref_recomen18`, `ref_recomen19`, `ref_recomen20`, `ref_recomen21`, `ref_recomen22`, `ref_recomen23`, `ref_recomen24`, `ref_recomen25`, `ref_recomen26`, `ref_recomen27`, `ref_recomen28`, `ref_recomen29`, `ref_recomen30`, `capacitacion`, `aceptacion_capacitacion`, `recomendaciones`, `proxima_inter`, `foto`, `id`) VALUES (' ', '', '', '', 'dsadasfs', 'Garantía', '', '', 'fafsafs', '', 'af', 'fs', 'afsa', '', '', '', '', 'eafdfdewarfew', '', '', 'wrwre', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'rrew', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 0)
ERROR - 2019-08-26 11:55:16 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 11:55:16 --> Severity: Notice --> Undefined index: id C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 250
ERROR - 2019-08-26 11:55:16 --> Query error: Column 'foto' cannot be null - Invalid query: INSERT INTO `bitacora_mtto` (`planta`, `modelo`, `maquina`, `fecha`, `motivo_asistencia`, `tipo`, `mantenimiento`, `consecutivo`, `des_acti1`, `des_acti2`, `des_acti3`, `des_acti4`, `des_acti5`, `des_acti6`, `des_acti7`, `des_acti8`, `des_acti9`, `des_acti10`, `des_acti11`, `des_acti12`, `des_acti13`, `des_acti14`, `des_acti15`, `reporto`, `ref_usadas1`, `ref_usadas2`, `ref_usadas3`, `ref_usadas4`, `ref_usadas5`, `ref_usadas6`, `ref_usadas7`, `ref_usadas8`, `ref_usadas9`, `ref_usadas10`, `ref_usadas11`, `ref_usadas12`, `ref_usadas13`, `ref_usadas14`, `ref_usadas15`, `ref_usadas16`, `ref_usadas17`, `ref_usadas18`, `ref_usadas19`, `ref_usadas20`, `ref_usadas21`, `ref_usadas22`, `ref_usadas23`, `ref_usadas24`, `ref_usadas25`, `ref_usadas26`, `ref_usadas27`, `ref_usadas28`, `ref_usadas29`, `ref_usadas30`, `ref_recomen1`, `ref_recomen2`, `ref_recomen3`, `ref_recomen4`, `ref_recomen5`, `ref_recomen6`, `ref_recomen7`, `ref_recomen8`, `ref_recomen9`, `ref_recomen10`, `ref_recomen11`, `ref_recomen12`, `ref_recomen13`, `ref_recomen14`, `ref_recomen15`, `ref_recomen16`, `ref_recomen17`, `ref_recomen18`, `ref_recomen19`, `ref_recomen20`, `ref_recomen21`, `ref_recomen22`, `ref_recomen23`, `ref_recomen24`, `ref_recomen25`, `ref_recomen26`, `ref_recomen27`, `ref_recomen28`, `ref_recomen29`, `ref_recomen30`, `capacitacion`, `aceptacion_capacitacion`, `recomendaciones`, `proxima_inter`, `foto`, `id`) VALUES (' ', '', '', '', 'dsadasfs', 'Garantía', '', '', 'fafsafs', '', 'af', 'fs', 'afsa', '', '', '', '', 'eafdfdewarfew', '', '', 'wrwre', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'rrew', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 0)
ERROR - 2019-08-26 12:14:21 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:14:21 --> Query error: Column 'foto' cannot be null - Invalid query: INSERT INTO `bitacora_mtto` (`planta`, `modelo`, `maquina`, `fecha`, `motivo_asistencia`, `tipo`, `mantenimiento`, `consecutivo`, `des_acti1`, `des_acti2`, `des_acti3`, `des_acti4`, `des_acti5`, `des_acti6`, `des_acti7`, `des_acti8`, `des_acti9`, `des_acti10`, `des_acti11`, `des_acti12`, `des_acti13`, `des_acti14`, `des_acti15`, `reporto`, `ref_usadas1`, `ref_usadas2`, `ref_usadas3`, `ref_usadas4`, `ref_usadas5`, `ref_usadas6`, `ref_usadas7`, `ref_usadas8`, `ref_usadas9`, `ref_usadas10`, `ref_usadas11`, `ref_usadas12`, `ref_usadas13`, `ref_usadas14`, `ref_usadas15`, `ref_usadas16`, `ref_usadas17`, `ref_usadas18`, `ref_usadas19`, `ref_usadas20`, `ref_usadas21`, `ref_usadas22`, `ref_usadas23`, `ref_usadas24`, `ref_usadas25`, `ref_usadas26`, `ref_usadas27`, `ref_usadas28`, `ref_usadas29`, `ref_usadas30`, `ref_recomen1`, `ref_recomen2`, `ref_recomen3`, `ref_recomen4`, `ref_recomen5`, `ref_recomen6`, `ref_recomen7`, `ref_recomen8`, `ref_recomen9`, `ref_recomen10`, `ref_recomen11`, `ref_recomen12`, `ref_recomen13`, `ref_recomen14`, `ref_recomen15`, `ref_recomen16`, `ref_recomen17`, `ref_recomen18`, `ref_recomen19`, `ref_recomen20`, `ref_recomen21`, `ref_recomen22`, `ref_recomen23`, `ref_recomen24`, `ref_recomen25`, `ref_recomen26`, `ref_recomen27`, `ref_recomen28`, `ref_recomen29`, `ref_recomen30`, `capacitacion`, `aceptacion_capacitacion`, `recomendaciones`, `proxima_inter`, `foto`, `id`) VALUES (' ', '', '', '', '5\r\n5', 'Garantía', '', '', '', '', '', '', '55', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '5555', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '55', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '1')
ERROR - 2019-08-26 12:15:57 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:17:30 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:17:30 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:23:09 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:23:09 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:25:30 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:26:07 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:40:21 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:45:17 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
ERROR - 2019-08-26 12:45:17 --> Severity: Notice --> Undefined index: foto C:\xampp\htdocs\master\application\controllers\BitacoraMtto.php 248
