<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-04-29 10:08:55 --> Página no encontrada: Assets/login
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-04-29 10:08:55 --> Página no encontrada: Assets/login
ERROR - 2021-04-29 10:08:55 --> Página no encontrada: Assets/login
ERROR - 2021-04-29 10:08:55 --> Página no encontrada: Assets/login
ERROR - 2021-04-29 10:08:55 --> Página no encontrada: Assets/login
ERROR - 2021-04-29 10:08:55 --> Página no encontrada: Assets/login
ERROR - 2021-04-29 10:08:56 --> Página no encontrada: Assets/login
ERROR - 2021-04-29 10:09:21 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1906
ERROR - 2021-04-29 12:21:19 --> Severity: error --> Exception: Call to undefined method CensoMaquinariaPojo::getId_clienteseguimiento() C:\xampp\htdocs\master\application\views\CensoMaquinaria\listarCensoMaquinaria.php 951
ERROR - 2021-04-29 12:21:53 --> Severity: error --> Exception: Call to undefined method CensoMaquinariaPojo::getId_clienteseguimiento() C:\xampp\htdocs\master\application\views\CensoMaquinaria\listarCensoMaquinaria.php 951
ERROR - 2021-04-29 12:21:55 --> Severity: error --> Exception: Call to undefined method CensoMaquinariaPojo::getId_clienteseguimiento() C:\xampp\htdocs\master\application\views\CensoMaquinaria\listarCensoMaquinaria.php 951
ERROR - 2021-04-29 13:18:59 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 13:19:34 --> Query error: Unknown column 'id_censomaquinaria' in 'where clause' - Invalid query: DELETE FROM `cliente_seguimiento`
WHERE `id_censomaquinaria` = '1'
ERROR - 2021-04-29 13:20:14 --> Severity: Notice --> Undefined property: CensoMaquinaria::$CensoMaquinaria C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:20:14 --> Severity: error --> Exception: Call to a member function get_by_id() on null C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:21:30 --> Severity: Notice --> Undefined property: CensoMaquinaria::$CensoMaquinaria C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:21:30 --> Severity: error --> Exception: Call to a member function get_by_id() on null C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:21:41 --> Severity: Notice --> Undefined property: CensoMaquinaria::$CensoMaquinaria C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:21:41 --> Severity: error --> Exception: Call to a member function get_by_id() on null C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:22:44 --> Severity: Notice --> Undefined property: CensoMaquinaria::$CensoMaquinaria C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:22:44 --> Severity: error --> Exception: Call to a member function get_by_id() on null C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:24:36 --> Severity: Notice --> Undefined property: CensoMaquinaria::$CensoMaquinaria C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:24:36 --> Severity: error --> Exception: Call to a member function get_by_id() on null C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:24:54 --> Severity: Notice --> Undefined property: CensoMaquinaria::$CensoMaquinaria C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:24:54 --> Severity: error --> Exception: Call to a member function get_by_id() on null C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:26:07 --> Severity: Notice --> Undefined property: CensoMaquinaria::$CensoMaquinaria C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 13:26:07 --> Severity: error --> Exception: Call to a member function get_by_id() on null C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 14:25:48 --> Severity: Notice --> Undefined property: CensoMaquinaria::$CensoMaquinaria C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 14:25:48 --> Severity: error --> Exception: Call to a member function get_by_id() on null C:\xampp\htdocs\master\application\controllers\CensoMaquinaria.php 548
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 40
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 51
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 53
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 54
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 55
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 56
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 57
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$modelo_maquina C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 70
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$numero_maquina C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 83
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cotizacion C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 116
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cotizacion C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 127
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cotizacion C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 130
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cotizacion C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 140
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cotizacion C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 143
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cotizacion C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 151
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cotizacion C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 154
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cotizacion C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 163
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$cotizacion C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 166
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$pedido C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 178
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$pedido C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 191
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$pedido C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 194
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$pedido C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 202
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$pedido C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 205
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$pedido C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 214
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$pedido C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 217
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$pedido C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 226
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$pedido C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 229
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$contrato C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 242
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$contrato C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 254
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$contrato C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 258
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$contrato C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 265
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$contrato C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 269
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$contrato C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 277
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$contrato C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 281
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$contrato C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 288
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$contrato C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 292
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$id_clienteseguimiento C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 317
ERROR - 2021-04-29 14:26:26 --> Severity: Notice --> Undefined property: stdClass::$id_clienteseguimiento C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 319
ERROR - 2021-04-29 14:35:40 --> Severity: Warning --> Use of undefined constant lo - assumed 'lo' (this will throw an Error in a future version of PHP) C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 20
ERROR - 2021-04-29 14:35:40 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 14:35:40 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 49
ERROR - 2021-04-29 14:35:40 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 51
ERROR - 2021-04-29 14:35:40 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 52
ERROR - 2021-04-29 14:35:40 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 53
ERROR - 2021-04-29 14:35:40 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 54
ERROR - 2021-04-29 14:35:40 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 55
ERROR - 2021-04-29 14:35:40 --> Severity: Notice --> Undefined property: stdClass::$id_clienteseguimiento C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 108
ERROR - 2021-04-29 14:35:40 --> Severity: Notice --> Undefined property: stdClass::$id_clienteseguimiento C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 110
ERROR - 2021-04-29 14:36:16 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 14:36:16 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 49
ERROR - 2021-04-29 14:36:16 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 51
ERROR - 2021-04-29 14:36:16 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 52
ERROR - 2021-04-29 14:36:16 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 53
ERROR - 2021-04-29 14:36:16 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 54
ERROR - 2021-04-29 14:36:16 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 55
ERROR - 2021-04-29 14:36:16 --> Severity: Notice --> Undefined property: stdClass::$id_clienteseguimiento C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 108
ERROR - 2021-04-29 14:36:16 --> Severity: Notice --> Undefined property: stdClass::$id_clienteseguimiento C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 110
ERROR - 2021-04-29 14:36:48 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 14:36:48 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 49
ERROR - 2021-04-29 14:36:48 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 51
ERROR - 2021-04-29 14:36:48 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 52
ERROR - 2021-04-29 14:36:48 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 53
ERROR - 2021-04-29 14:36:48 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 54
ERROR - 2021-04-29 14:36:48 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 55
ERROR - 2021-04-29 14:37:13 --> Página no encontrada: CensoMaquinarias/updatedata
ERROR - 2021-04-29 14:37:13 --> Página no encontrada: Assets/images
ERROR - 2021-04-29 14:37:13 --> Página no encontrada: Assets/images
ERROR - 2021-04-29 14:38:51 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 14:38:51 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 49
ERROR - 2021-04-29 14:38:51 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 51
ERROR - 2021-04-29 14:38:51 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 52
ERROR - 2021-04-29 14:38:51 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 53
ERROR - 2021-04-29 14:38:51 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 54
ERROR - 2021-04-29 14:38:51 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 55
ERROR - 2021-04-29 14:39:21 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:39:34 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:40:05 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:41:49 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:41:55 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:42:05 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:43:09 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:43:10 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:43:22 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:43:23 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:49:28 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:49:29 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:49:38 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:53:27 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:54:08 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:57:21 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:57:22 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:57:51 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 14:58:58 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:00:45 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:13:30 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:13:31 --> Query error: Column 'nombre_dueno' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ERROR - 2021-04-29 15:13:34 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:13:48 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:14:01 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:16:31 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:17:50 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:19:12 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:19:13 --> Query error: Column 'nombre_dueno' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ERROR - 2021-04-29 15:19:18 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:19:24 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:19:25 --> Query error: Column 'nombre_dueno' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ERROR - 2021-04-29 15:19:27 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:19:57 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:19:58 --> Query error: Column 'nombre_dueno' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ERROR - 2021-04-29 15:19:59 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:20:41 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:20:42 --> Query error: Column 'nombre_dueno' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '')
ERROR - 2021-04-29 15:22:06 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:22:08 --> Query error: Column 'nombre_ceo' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '')
ERROR - 2021-04-29 15:22:12 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:22:23 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:22:26 --> Query error: Column 'nombre_gerente' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '')
ERROR - 2021-04-29 15:22:28 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:22:38 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:22:39 --> Query error: Column 'nombre_produccion' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '')
ERROR - 2021-04-29 15:22:41 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:22:58 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:23:00 --> Query error: Column 'correo_empresarial_mmto' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '')
ERROR - 2021-04-29 15:23:02 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:23:13 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:23:14 --> Query error: Column 'correo_empresarial_mmto' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '')
ERROR - 2021-04-29 15:23:17 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:30:10 --> Query error: Column 'correo_empresarial_mmto' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '')
ERROR - 2021-04-29 15:30:21 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:30:23 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:30:37 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:30:46 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:30:47 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:30:47 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:30:47 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:30:50 --> Query error: Column 'correo_empresarial_mmto' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '')
ERROR - 2021-04-29 15:30:54 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:31:31 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:33:51 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:33:53 --> Query error: Column 'correo_empresarial_mmto' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', '', '', '', '', '', '', '', '', '', '', '')
ERROR - 2021-04-29 15:49:20 --> Query error: Unknown column 'correo_empresarial_mmto' in 'field list' - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ERROR - 2021-04-29 15:49:27 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:49:28 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:49:29 --> Query error: Unknown column 'correo_empresarial_mmto' in 'field list' - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mmto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', '', '', '', '', '', '', '', '', '', '', '')
ERROR - 2021-04-29 15:51:28 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:58:16 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:58:17 --> Query error: Column 'estatus_cliente' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mtto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, '', '', '', '', '', '', '', '', '', '', '', '', '')
ERROR - 2021-04-29 15:58:36 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:58:37 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 15:58:38 --> Query error: Column 'tamano_cliente' cannot be null - Invalid query: INSERT INTO `censo_maquinaria` (`grupo`, `empresa`, `estado`, `ciudad_municipio`, `nombre_dueno`, `celular_dueno`, `correo_empresarial_dueno`, `correo_personal_dueno`, `nombre_ceo`, `celular_ceo`, `correo_empresarial_ceo`, `correo_personal_ceo`, `nombre_gerente`, `celular_gerente`, `correo_empresarial_gerente`, `correo_personal_gerente`, `nombre_produccion`, `celular_produccion`, `correo_empresarial_produccion`, `correo_personal_produccion`, `nombre_mtto`, `celular_mtto`, `correo_empresarial_mtto`, `correo_personal_mtto`, `nombre_compras`, `celular_compras`, `correo_empresarial_compras`, `correo_personal_compras`, `nombre_ventas`, `celular_ventas`, `correo_empresarial_ventas`, `correo_personal_ventas`, `nombre_otros`, `celular_otros`, `correo_empresarial_otros`, `correo_personal_otros`, `tipo_de_cliente`, `asesor`, `estatus_cliente`, `tamano_cliente`, `tipo_mercado`, `volumen_produccion`, `necesidad`, `compromiso`, `notas`, `info_maquina_1`, `info_maquina_2`, `info_maquina_3`, `info_maquina_4`, `info_maquina_5`, `info_maquina_6`, `info_maquina_7`, `refacciones`) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', '', '', '', '', '', '', '', '', '')
ERROR - 2021-04-29 15:59:04 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:00:05 --> Severity: Notice --> Undefined property: stdClass::$correo_empresarial_mmto C:\xampp\htdocs\master\application\models\CensoMaquinaria\CensoMaquinariaModelo.php 163
ERROR - 2021-04-29 16:00:12 --> Severity: Notice --> Undefined property: stdClass::$correo_empresarial_mmto C:\xampp\htdocs\master\application\models\CensoMaquinaria\CensoMaquinariaModelo.php 163
ERROR - 2021-04-29 16:00:57 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:02:36 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:04:58 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:32:10 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:32:48 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:38:54 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:39:05 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:41:05 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:41:06 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:41:27 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:41:27 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:41:55 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:41:56 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:44:02 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:44:07 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:44:28 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:44:29 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:44:49 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:44:49 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:46:02 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:48:26 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:50:58 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:52:12 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 16:52:24 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 17:02:22 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 17:04:20 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 17:17:43 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:17:43 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 49
ERROR - 2021-04-29 17:17:43 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 51
ERROR - 2021-04-29 17:17:43 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 52
ERROR - 2021-04-29 17:17:43 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 53
ERROR - 2021-04-29 17:17:43 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 54
ERROR - 2021-04-29 17:17:43 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 55
ERROR - 2021-04-29 17:18:30 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:18:30 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 49
ERROR - 2021-04-29 17:18:30 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 51
ERROR - 2021-04-29 17:18:30 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 52
ERROR - 2021-04-29 17:18:30 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 53
ERROR - 2021-04-29 17:18:30 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 54
ERROR - 2021-04-29 17:18:30 --> Severity: Notice --> Undefined property: stdClass::$nivel C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 55
ERROR - 2021-04-29 17:19:23 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:21:59 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:22:35 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:24:34 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:24:40 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:24:41 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:24:42 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:24:43 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:24:43 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:24:43 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:25:10 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:25:11 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:25:23 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:46:42 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:47:01 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:47:12 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 38
ERROR - 2021-04-29 17:48:18 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 17:50:32 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 17:51:34 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 17:52:37 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 17:53:14 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 17:53:36 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 17:53:57 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 17:55:02 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 17:55:02 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 17:55:51 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 17:57:02 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 18:02:38 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 18:04:17 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 231
ERROR - 2021-04-29 18:05:36 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1063
ERROR - 2021-04-29 18:08:41 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1063
ERROR - 2021-04-29 18:11:12 --> Severity: error --> Exception: syntax error, unexpected '?>', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 894
ERROR - 2021-04-29 18:12:34 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1063
ERROR - 2021-04-29 18:15:30 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1063
ERROR - 2021-04-29 18:19:21 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1154
ERROR - 2021-04-29 18:19:43 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1154
ERROR - 2021-04-29 18:19:57 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1154
ERROR - 2021-04-29 18:20:19 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1154
ERROR - 2021-04-29 18:20:19 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1154
ERROR - 2021-04-29 18:20:19 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1154
ERROR - 2021-04-29 18:20:20 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1154
ERROR - 2021-04-29 18:20:37 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1154
ERROR - 2021-04-29 18:20:51 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1154
ERROR - 2021-04-29 18:21:41 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1156
ERROR - 2021-04-29 18:22:40 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1158
ERROR - 2021-04-29 18:23:04 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1158
ERROR - 2021-04-29 18:25:53 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1172
ERROR - 2021-04-29 18:26:20 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1171
ERROR - 2021-04-29 18:27:59 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1171
ERROR - 2021-04-29 18:28:14 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1171
ERROR - 2021-04-29 18:30:04 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1158
ERROR - 2021-04-29 18:38:17 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1158
ERROR - 2021-04-29 18:51:59 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1158
ERROR - 2021-04-29 20:17:17 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 20:17:41 --> Página no encontrada: Assets/font
ERROR - 2021-04-29 20:17:47 --> Severity: Notice --> Undefined property: stdClass::$cliente C:\xampp\htdocs\master\application\views\CensoMaquinaria\editar.php 1158
