<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-07-05 09:16:22 --> Página no encontrada: Assets/login
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-07-05 09:16:22 --> Página no encontrada: Assets/login
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-07-05 09:16:22 --> Página no encontrada: Assets/login
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-07-05 09:16:22 --> Página no encontrada: Assets/login
ERROR - 2021-07-05 09:16:23 --> Página no encontrada: Assets/login
ERROR - 2021-07-05 09:16:23 --> Página no encontrada: Assets/login
ERROR - 2021-07-05 09:16:23 --> Página no encontrada: Assets/login
ERROR - 2021-07-05 09:16:34 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1906
ERROR - 2021-07-05 10:34:30 --> Severity: Notice --> Trying to get property 'qty' of non-object C:\xampp\htdocs\master\application\models\Model_products.php 286
ERROR - 2021-07-05 10:34:30 --> Severity: Notice --> Trying to get property 'cantidad' of non-object C:\xampp\htdocs\master\application\models\Model_products.php 298
ERROR - 2021-07-05 10:34:36 --> Severity: Notice --> Trying to get property 'qty' of non-object C:\xampp\htdocs\master\application\models\Model_products.php 286
ERROR - 2021-07-05 10:34:36 --> Severity: Notice --> Trying to get property 'cantidad' of non-object C:\xampp\htdocs\master\application\models\Model_products.php 298
ERROR - 2021-07-05 10:34:52 --> Severity: Notice --> Trying to get property 'qty' of non-object C:\xampp\htdocs\master\application\models\Model_products.php 286
ERROR - 2021-07-05 10:34:52 --> Severity: Notice --> Trying to get property 'cantidad' of non-object C:\xampp\htdocs\master\application\models\Model_products.php 298
ERROR - 2021-07-05 11:13:59 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 11:14:15 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 11:14:16 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_prospeccion C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 174
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamadas_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 175
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_contacto_cliente C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 176
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$llamdas_hechas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 177
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_llamada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 178
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$numero_visitas C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 179
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$fecha_ult_visita C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 180
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$monto_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 181
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$modelo_cotizado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 182
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$ventas_cerrada C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 183
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_asignado C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 184
ERROR - 2021-07-05 11:30:53 --> Severity: Notice --> Undefined property: stdClass::$cliente_nuevo C:\xampp\htdocs\master\application\models\ClienteSeguimiento\ClienteSeguimientoModelo.php 185
ERROR - 2021-07-05 11:33:12 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`fecha_contacto_cliente cliente_seguimiento`.`llamdas_hechas cliente_seguimient' at line 1 - Invalid query: SELECT `cliente_seguimiento`.`id_clienteseguimiento`, `cliente_seguimiento`.`cliente`, `cliente_seguimiento`.`nivel`, `cliente_seguimiento`.`necesidad`, `cliente_seguimiento`.`compromiso`, `cliente_seguimiento`.`notas`, `cliente_seguimiento`.`modelo_maquina`, `cliente_seguimiento`.`numero_maquina`, `cliente_seguimiento`.`valor_cotizacion`, `cliente_seguimiento`.`fecha_ultima_visita`, `cliente_seguimiento`.`cotizacion`, `cliente_seguimiento`.`pedido`, `cliente_seguimiento`.`contrato`, `users`.`first_name`, `cliente_seguimiento`.`fecha_prospeccion cliente_seguimiento`.`llamadas_cliente cliente_seguimiento`.`fecha_contacto_cliente cliente_seguimiento`.`llamdas_hechas cliente_seguimiento`.`fecha_ult_llamada cliente_seguimiento`.`numero_visi cliente_seguimiento`.`fecha_prospeccion cliente_seguimientotas cliente_seguimiento`.`fecha_ult_visita cliente_seguimiento`.`monto_cotizado cliente_seguimiento`.`modelo_cotizado cliente_seguimiento`.`ventas_cerrada cliente_seguimiento`.`cliente_asignado` `cliente_seguimiento`.`cliente_nuevo`
FROM `cliente_seguimiento`
JOIN `users` ON `cliente_seguimiento`.`id`=`users`.`id`
ORDER BY `id_clienteseguimiento` DESC
ERROR - 2021-07-05 11:34:23 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 15:50:09 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 15:51:32 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 15:52:08 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 15:52:33 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 15:52:33 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 15:54:57 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 16:18:08 --> Severity: Notice --> Trying to get property 'qty' of non-object C:\xampp\htdocs\master\application\models\Model_products.php 286
ERROR - 2021-07-05 16:18:08 --> Severity: Notice --> Trying to get property 'cantidad' of non-object C:\xampp\htdocs\master\application\models\Model_products.php 298
ERROR - 2021-07-05 17:28:19 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 17:50:07 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 18:22:24 --> Página no encontrada: Assets/font
ERROR - 2021-07-05 18:24:53 --> Página no encontrada: Assets/font
