<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2018-12-11 00:28:16 --> Severity: Notice --> Undefined variable: objPHPExcel C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 626
ERROR - 2018-12-11 00:28:16 --> Severity: error --> Exception: Call to a member function getProperties() on null C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 626
ERROR - 2018-12-11 15:37:11 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): No se puede establecer una conexi�n ya que el equipo de destino deneg� expresamente dicha conexi�n.
 C:\xampp\htdocs\master\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2018-12-11 15:37:11 --> Unable to connect to the database
ERROR - 2018-12-11 15:37:33 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): No se puede establecer una conexi�n ya que el equipo de destino deneg� expresamente dicha conexi�n.
 C:\xampp\htdocs\master\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2018-12-11 15:37:33 --> Unable to connect to the database
ERROR - 2018-12-11 15:38:05 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1888
ERROR - 2018-12-11 15:38:05 --> Severity: Warning --> setcookie() expects parameter 3 to be integer, float given C:\xampp\htdocs\master\system\core\Input.php 408
ERROR - 2018-12-11 15:38:09 --> Severity: Notice --> Undefined variable: descripcion C:\xampp\htdocs\master\application\views\ClienteRefacciones\listarClienteRefacciones.php 198
ERROR - 2018-12-11 15:38:09 --> Severity: error --> Exception: Method name must be a string C:\xampp\htdocs\master\application\views\ClienteRefacciones\listarClienteRefacciones.php 198
ERROR - 2018-12-11 15:44:16 --> Página no encontrada: Assets/images
ERROR - 2018-12-11 18:26:58 --> Severity: Notice --> Undefined property: stdClass::$fecha_corte_rotacion C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 346
ERROR - 2018-12-11 18:26:58 --> Severity: Notice --> Undefined property: stdClass::$fecha_corte_rotacion C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 346
ERROR - 2018-12-11 18:26:58 --> Severity: Notice --> Undefined property: stdClass::$fecha_corte_rotacion C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 346
ERROR - 2018-12-11 18:26:58 --> Severity: Notice --> Undefined property: stdClass::$fecha_corte_rotacion C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 346
ERROR - 2018-12-11 18:28:35 --> Severity: Notice --> Undefined property: stdClass::$fecha_corte_rotacion C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 346
ERROR - 2018-12-11 18:28:35 --> Severity: Notice --> Undefined property: stdClass::$fecha_corte_rotacion C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 346
ERROR - 2018-12-11 18:28:35 --> Severity: Notice --> Undefined property: stdClass::$fecha_corte_rotacion C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 346
ERROR - 2018-12-11 18:28:35 --> Severity: Notice --> Undefined property: stdClass::$fecha_corte_rotacion C:\xampp\htdocs\master\application\controllers\ExportarExcel.php 346
ERROR - 2018-12-11 21:14:36 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 21:14:41 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 21:14:44 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 21:14:46 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 21:14:49 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 21:14:54 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 21:14:59 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 21:15:01 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 21:15:05 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 21:15:17 --> Severity: Notice --> Undefined variable: success C:\xampp\htdocs\master\application\models\User_model.php 327
ERROR - 2018-12-11 22:15:23 --> Severity: Notice --> Undefined index: cliente_sae_dolares C:\xampp\htdocs\master\application\controllers\Cliente.php 114
ERROR - 2018-12-11 22:15:23 --> Query error: Column 'cliente_sae_dolares' cannot be null - Invalid query: INSERT INTO `cliente` (`grupo`, `cliente`, `cliente_sae_dolares`, `cliente_sae`, `razon_soc`, `rfc`, `direccion`, `tel_cel`, `extension`, `correo`, `correo1`, `correo2`, `correo3`, `moneda`, `cta_banc`, `vendedor_refacciones`, `vendedor_maquinaria`, `uso_de_cfdi`, `metodo_pago`, `direccion_entrega`, `id`) VALUES ('', '', NULL, '7', '879', '897', '879', '897', '897', '', '879', '89', '897', '', '897', '', '', '', '', '879', '1')
ERROR - 2018-12-11 22:16:51 --> Severity: Notice --> Undefined index: cliente_sae_dolares C:\xampp\htdocs\master\application\controllers\Cliente.php 115
ERROR - 2018-12-11 22:16:51 --> Query error: Column 'cliente_sae_dolares' cannot be null - Invalid query: INSERT INTO `cliente` (`grupo`, `cliente`, `cliente_sae`, `cliente_sae_dolares`, `razon_soc`, `rfc`, `direccion`, `tel_cel`, `extension`, `correo`, `correo1`, `correo2`, `correo3`, `moneda`, `cta_banc`, `vendedor_refacciones`, `vendedor_maquinaria`, `uso_de_cfdi`, `metodo_pago`, `direccion_entrega`, `id`) VALUES ('', '', '7', NULL, '879', '897', '879', '897', '897', '', '879', '89', '897', '', '897', '', '', '', '', '879', '1')
ERROR - 2018-12-11 22:16:55 --> Severity: Notice --> Undefined index: cliente_sae_dolares C:\xampp\htdocs\master\application\controllers\Cliente.php 115
ERROR - 2018-12-11 22:16:55 --> Query error: Column 'cliente_sae_dolares' cannot be null - Invalid query: INSERT INTO `cliente` (`grupo`, `cliente`, `cliente_sae`, `cliente_sae_dolares`, `razon_soc`, `rfc`, `direccion`, `tel_cel`, `extension`, `correo`, `correo1`, `correo2`, `correo3`, `moneda`, `cta_banc`, `vendedor_refacciones`, `vendedor_maquinaria`, `uso_de_cfdi`, `metodo_pago`, `direccion_entrega`, `id`) VALUES ('', '', '7', NULL, '879', '897', '879', '897', '897', '', '879', '89', '897', '', '897', '', '', '', '', '879', '1')
ERROR - 2018-12-11 22:17:36 --> Severity: Notice --> Undefined index: cliente_sae_dolares C:\xampp\htdocs\master\application\controllers\Cliente.php 115
ERROR - 2018-12-11 22:17:36 --> Query error: Column 'cliente_sae_dolares' cannot be null - Invalid query: INSERT INTO `cliente` (`grupo`, `cliente`, `cliente_sae`, `cliente_sae_dolares`, `razon_soc`, `rfc`, `direccion`, `tel_cel`, `extension`, `correo`, `correo1`, `correo2`, `correo3`, `moneda`, `cta_banc`, `vendedor_refacciones`, `vendedor_maquinaria`, `uso_de_cfdi`, `metodo_pago`, `direccion_entrega`, `id`) VALUES ('', '', '7', NULL, '879', '897', '879', '897', '897', '', '879', '89', '897', '', '897', '', '', '', '', '879', '1')
ERROR - 2018-12-11 22:17:40 --> Severity: Notice --> Undefined index: cliente_sae_dolares C:\xampp\htdocs\master\application\controllers\Cliente.php 115
ERROR - 2018-12-11 22:17:40 --> Query error: Column 'cliente_sae_dolares' cannot be null - Invalid query: INSERT INTO `cliente` (`grupo`, `cliente`, `cliente_sae`, `cliente_sae_dolares`, `razon_soc`, `rfc`, `direccion`, `tel_cel`, `extension`, `correo`, `correo1`, `correo2`, `correo3`, `moneda`, `cta_banc`, `vendedor_refacciones`, `vendedor_maquinaria`, `uso_de_cfdi`, `metodo_pago`, `direccion_entrega`, `id`) VALUES ('', '', '7', NULL, '879', '897', '879', '897', '897', '', '879', '89', '897', '', '897', '', '', '', '', '879', '1')
ERROR - 2018-12-11 22:17:52 --> Severity: Notice --> Undefined index: cliente_sae_dolares C:\xampp\htdocs\master\application\controllers\Cliente.php 115
ERROR - 2018-12-11 22:17:52 --> Query error: Column 'cliente_sae_dolares' cannot be null - Invalid query: INSERT INTO `cliente` (`grupo`, `cliente`, `cliente_sae`, `cliente_sae_dolares`, `razon_soc`, `rfc`, `direccion`, `tel_cel`, `extension`, `correo`, `correo1`, `correo2`, `correo3`, `moneda`, `cta_banc`, `vendedor_refacciones`, `vendedor_maquinaria`, `uso_de_cfdi`, `metodo_pago`, `direccion_entrega`, `id`) VALUES ('', '7', '7', NULL, '7', '7', '7', '7', '7', '7', '7', '7', '7', '', '7', '', '', '', '', '7', '1')
ERROR - 2018-12-11 23:21:44 --> Query error: Unknown column 'cta_banc_dolares' in 'field list' - Invalid query: INSERT INTO `cliente` (`grupo`, `cliente`, `cliente_sae`, `cliente_sae_dolares`, `razon_soc`, `rfc`, `direccion`, `tel_cel`, `extension`, `correo`, `correo1`, `correo2`, `correo3`, `moneda`, `cta_banc`, `cta_banc_dolares`, `vendedor_refacciones`, `vendedor_maquinaria`, `forma_pago`, `metodo_pago`, `uso_de_cfdi`, `direccion_entrega`, `id`) VALUES ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', 'Pesos', '14', '15', 'Carlos Hernández Maza', 'Sergio Peñafiel Soto', '16', '01-Eféctivo', 'G01 Adquisión de mercancías', '17', '1')
ERROR - 2018-12-11 23:22:24 --> Severity: error --> Exception: Too few arguments to function ClientePojo::__construct(), 22 passed in C:\xampp\htdocs\master\application\models\Cliente\ClienteModelo.php on line 77 and exactly 23 expected C:\xampp\htdocs\master\application\models\Cliente\ClientePojo.php 35
