<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-01-11 09:23:32 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1888
ERROR - 2019-01-11 09:23:32 --> Severity: Warning --> setcookie() expects parameter 3 to be integer, float given C:\xampp\htdocs\master\system\core\Input.php 408
ERROR - 2019-01-11 09:24:45 --> Severity: Warning --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() C:\xampp\htdocs\master\system\libraries\Email.php 1888
ERROR - 2019-01-11 09:24:45 --> Severity: Warning --> setcookie() expects parameter 3 to be integer, float given C:\xampp\htdocs\master\system\core\Input.php 408
ERROR - 2019-01-11 16:25:10 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 57
ERROR - 2019-01-11 16:25:10 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 61
ERROR - 2019-01-11 16:25:18 --> Severity: Notice --> Undefined index: archivo1 C:\xampp\htdocs\master\application\controllers\Bitacora.php 519
ERROR - 2019-01-11 16:25:18 --> Severity: Notice --> Undefined index: observacion C:\xampp\htdocs\master\application\controllers\Bitacora.php 520
ERROR - 2019-01-11 16:27:08 --> Severity: Notice --> Undefined variable: file C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 55
ERROR - 2019-01-11 16:27:08 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 16:27:08 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 16:28:03 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 16:28:03 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 16:28:09 --> Severity: Notice --> Undefined index: observacion C:\xampp\htdocs\master\application\controllers\Bitacora.php 520
ERROR - 2019-01-11 16:28:44 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 16:28:44 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 16:28:47 --> Severity: Notice --> Undefined index: observacion C:\xampp\htdocs\master\application\controllers\Bitacora.php 520
ERROR - 2019-01-11 16:29:41 --> Severity: Notice --> Undefined index: cliente C:\xampp\htdocs\master\application\controllers\Bitacora.php 517
ERROR - 2019-01-11 16:29:41 --> Severity: Notice --> Undefined index: archivo1 C:\xampp\htdocs\master\application\controllers\Bitacora.php 519
ERROR - 2019-01-11 16:31:46 --> Severity: Notice --> Undefined index: cliente C:\xampp\htdocs\master\application\controllers\Bitacora.php 517
ERROR - 2019-01-11 17:00:44 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:00:44 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:02:39 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:02:39 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:07:30 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:07:30 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:07:32 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:07:32 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:07:33 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:07:33 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:07:43 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:07:43 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:08:03 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:08:03 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:08:16 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 63
ERROR - 2019-01-11 17:08:16 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 67
ERROR - 2019-01-11 17:08:29 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:08:29 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:10:15 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:10:15 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:10:28 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:10:28 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:10:30 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:10:30 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:10:39 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:10:39 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 68
ERROR - 2019-01-11 17:10:58 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:10:58 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:11:23 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 60
ERROR - 2019-01-11 17:11:23 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:13:59 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 60
ERROR - 2019-01-11 17:13:59 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 64
ERROR - 2019-01-11 17:18:50 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:18:50 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:12 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:12 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:13 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:13 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:13 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:13 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:13 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:13 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:14 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:14 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:14 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:14 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:15 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:15 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:15 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:15 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:15 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:15 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:31 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:31 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:34 --> Severity: Notice --> Undefined index: observacion C:\xampp\htdocs\master\application\controllers\Bitacora.php 520
ERROR - 2019-01-11 17:19:37 --> Severity: Notice --> Undefined variable: fecha_insercion C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 62
ERROR - 2019-01-11 17:19:37 --> Severity: Notice --> Undefined variable: fecha_modificar C:\xampp\htdocs\master\application\views\Bitacora\modificarBitacora.php 66
ERROR - 2019-01-11 17:19:43 --> Severity: Notice --> Undefined index: observacion C:\xampp\htdocs\master\application\controllers\Bitacora.php 520
ERROR - 2019-01-11 17:20:30 --> Severity: Notice --> Undefined index: cliente C:\xampp\htdocs\master\application\controllers\Bitacora.php 517
ERROR - 2019-01-11 17:21:13 --> Severity: Notice --> Undefined index: cliente C:\xampp\htdocs\master\application\controllers\Bitacora.php 517
